//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thunders.TechTest.ApiService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thunders.TechTest.ApiService.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O argumento não pode ser nulo ou vazio..
        /// </summary>
        internal static string ArgumentCannotNullEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao processar mensagem..
        /// </summary>
        internal static string ErrorProcessingMessage {
            get {
                return ResourceManager.GetString("ErrorProcessingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho máximo de {0}..
        /// </summary>
        internal static string MaximumLength {
            get {
                return ResourceManager.GetString("MaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem de uso de pedágio enviada para a praça {0}..
        /// </summary>
        internal static string MessageSentPlaza {
            get {
                return ResourceManager.GetString("MessageSentPlaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} precisa ser preenchido..
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report {0} processed successfully..
        /// </summary>
        internal static string ReportProcessedSuccessfully {
            get {
                return ResourceManager.GetString("ReportProcessedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado do relatório não encontrado..
        /// </summary>
        internal static string ReportResultNotFound {
            get {
                return ResourceManager.GetString("ReportResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciada a geração do relatório  de  valor total por hora por cidade..
        /// </summary>
        internal static string StartedHourlyCityReportGeneration {
            get {
                return ResourceManager.GetString("StartedHourlyCityReportGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciada a geração do relatório das praças que mais faturaram por mês..
        /// </summary>
        internal static string StartedPlazaReportGeneration {
            get {
                return ResourceManager.GetString("StartedPlazaReportGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciada a geração do relatório de quantos tipos de veículos passaram em uma determinada praça..
        /// </summary>
        internal static string StartedVehicleCountReportGeneration {
            get {
                return ResourceManager.GetString("StartedVehicleCountReportGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso de pedágio registrado para a praça {0}..
        /// </summary>
        internal static string TollRecordedPlaza {
            get {
                return ResourceManager.GetString("TollRecordedPlaza", resourceCulture);
            }
        }
    }
}
